#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N app-clean-parcellation
#PBS -V

# clean parcellation
time singularity exec -e docker://brainlife/dipy:1.4.0 ./clean_parcellation.py

key_txt=`jq -r '.key' config.json`
[ ! -f ./output/parc.nii.gz ] && echo "something went wrong. check derivatives" && exit 1 || echo "cleaning complete" && cp ${key_txt} ./output/ && exit 0
